import type { FormContractProjectConfig } from '@formly-contract/workspace';

type TestAppFieldTypeProfiles = NonNullable<
  FormContractProjectConfig['fieldTypeProfiles']
>;

const declaredPart = (
  name: string,
  role: string,
  cardinality: 'one' | 'many' = 'one',
) => ({ name, role, cardinality, evidence: 'declared' as const });

export const TEST_APP_FIELD_TYPE_PROFILES: TestAppFieldTypeProfiles = {
  schemaVersion: '0.4.0',
  id: 'fixture.single-angular-fields',
  version: 1,
  profiles: [
    {
      identity: { id: 'fixture.currency', version: 1 },
      semanticType: 'currency',
      valueShape: 'scalar',
      evidence: 'declared',
      parts: [declaredPart('control', 'spinbutton')],
      interaction: {
        kind: 'fill',
        operation: 'fill',
        controlPart: 'control',
      },
      valueDomain: { kind: 'not-applicable', evidence: 'declared' },
      driver: {
        kind: 'generic',
        id: 'generic.fill',
        version: 1,
        capabilities: ['fill'],
      },
      effectCapabilities: { targetProperties: [], readiness: [] },
      unknowns: [],
    },
    {
      identity: { id: 'fixture.rating', version: 1 },
      semanticType: 'single-choice',
      valueShape: 'scalar',
      evidence: 'declared',
      parts: [
        declaredPart('group', 'radiogroup'),
        declaredPart('option', 'radio', 'many'),
      ],
      interaction: {
        kind: 'choice',
        operation: 'check',
        optionPart: 'option',
      },
      valueDomain: {
        kind: 'runtime-enumerable',
        completeness: 'scenario',
        optionPart: 'option',
        evidence: 'declared',
      },
      driver: {
        kind: 'application',
        id: 'fixture.rating-driver',
        version: 1,
        capabilities: ['check'],
      },
      effectCapabilities: { targetProperties: [], readiness: [] },
      unknowns: [],
    },
    {
      identity: { id: 'fixture.repeat-section', version: 1 },
      semanticType: 'repeater',
      valueShape: 'array',
      evidence: 'declared',
      parts: [
        declaredPart('add', 'button'),
        declaredPart('item', 'group', 'many'),
      ],
      interaction: {
        kind: 'repeater',
        operation: 'add-item',
        addPart: 'add',
        itemPart: 'item',
      },
      valueDomain: { kind: 'not-applicable', evidence: 'declared' },
      driver: {
        kind: 'generic',
        id: 'generic.repeater',
        version: 1,
        capabilities: ['add-item'],
      },
      effectCapabilities: { targetProperties: [], readiness: [] },
      unknowns: [],
    },
    {
      identity: { id: 'fixture.button-toggle', version: 1 },
      semanticType: 'single-choice',
      valueShape: 'scalar',
      evidence: 'declared',
      parts: [
        declaredPart('group', 'radiogroup'),
        declaredPart('option', 'radio', 'many'),
      ],
      interaction: {
        kind: 'choice',
        operation: 'check',
        optionPart: 'option',
      },
      valueDomain: {
        kind: 'projected',
        source: 'adapter',
        completeness: 'complete',
        collectionPath: 'props.options',
        labelPath: 'label',
        valuePath: 'value',
        disabledPath: 'disabled',
        evidence: 'declared',
      },
      driver: {
        kind: 'generic',
        id: 'generic.choice',
        version: 1,
        capabilities: ['check'],
      },
      effectCapabilities: { targetProperties: ['options'], readiness: [] },
      unknowns: [],
    },
    {
      identity: { id: 'fixture.overlay-select', version: 1 },
      semanticType: 'single-choice',
      valueShape: 'scalar',
      evidence: 'declared',
      parts: [
        declaredPart('trigger', 'button'),
        declaredPart('popup', 'listbox'),
        declaredPart('option', 'option', 'many'),
      ],
      interaction: {
        kind: 'choice',
        operation: 'select-from-overlay',
        triggerPart: 'trigger',
        popupPart: 'popup',
        optionPart: 'option',
      },
      valueDomain: {
        kind: 'projected',
        source: 'adapter',
        completeness: 'scenario',
        collectionPath: 'props.options',
        labelPath: 'label',
        valuePath: 'value',
        disabledPath: 'disabled',
        evidence: 'declared',
      },
      driver: {
        kind: 'generic',
        id: 'generic.choice',
        version: 1,
        capabilities: ['select-from-overlay'],
      },
      effectCapabilities: { targetProperties: ['options'], readiness: [] },
      unknowns: [
        {
          aspect: 'runtime-states',
          reason: 'The fixture replaces options when the toggle changes.',
          evidence: 'declared',
        },
      ],
    },
    {
      identity: { id: 'fixture.autocomplete', version: 1 },
      semanticType: 'single-choice',
      valueShape: 'object',
      evidence: 'declared',
      parts: [
        declaredPart('query', 'combobox'),
        declaredPart('popup', 'listbox'),
        declaredPart('option', 'option', 'many'),
      ],
      interaction: {
        kind: 'autocomplete',
        operation: 'type-and-pick',
        queryPart: 'query',
        popupPart: 'popup',
        optionPart: 'option',
      },
      valueDomain: {
        kind: 'projected',
        source: 'adapter',
        completeness: 'complete',
        collectionPath: 'props.options',
        labelPath: 'label',
        valuePath: 'value',
        disabledPath: 'disabled',
        evidence: 'declared',
      },
      driver: {
        kind: 'generic',
        id: 'generic.autocomplete',
        version: 1,
        capabilities: ['type-and-pick'],
      },
      effectCapabilities: { targetProperties: ['options'], readiness: [] },
      unknowns: [],
    },
    {
      identity: { id: 'fixture.table-select', version: 1 },
      semanticType: 'multi-choice',
      valueShape: 'array',
      evidence: 'declared',
      parts: [
        declaredPart('row', 'row', 'many'),
        declaredPart('selection', 'checkbox', 'many'),
      ],
      interaction: {
        kind: 'row-selection',
        operation: 'select-row',
        rowPart: 'row',
        selectionPart: 'selection',
      },
      valueDomain: {
        kind: 'projected',
        source: 'adapter',
        completeness: 'complete',
        collectionPath: 'props.rowOptions',
        labelPath: 'label',
        valuePath: 'id',
        evidence: 'declared',
      },
      driver: {
        kind: 'generic',
        id: 'generic.row-selection',
        version: 1,
        capabilities: ['select-row'],
      },
      effectCapabilities: { targetProperties: [], readiness: [] },
      unknowns: [],
    },
    {
      identity: { id: 'fixture.expandable-repeater', version: 1 },
      semanticType: 'repeater',
      valueShape: 'array',
      evidence: 'declared',
      parts: [
        declaredPart('add', 'button'),
        declaredPart('item', 'group', 'many'),
        declaredPart('expand', 'button', 'many'),
      ],
      interaction: {
        kind: 'repeater',
        operation: 'expand-item',
        addPart: 'add',
        itemPart: 'item',
        expandPart: 'expand',
      },
      valueDomain: { kind: 'not-applicable', evidence: 'declared' },
      driver: {
        kind: 'generic',
        id: 'generic.repeater',
        version: 1,
        capabilities: ['expand-item'],
      },
      effectCapabilities: { targetProperties: [], readiness: [] },
      unknowns: [],
    },
  ],
  registrations: [
    ['autocomplete', 'fixture.autocomplete'],
    ['button-toggle', 'fixture.button-toggle'],
    ['currency', 'fixture.currency'],
    ['expandable-repeater', 'fixture.expandable-repeater'],
    ['overlay-select', 'fixture.overlay-select'],
    ['rating', 'fixture.rating'],
    ['repeat-section', 'fixture.repeat-section'],
    ['table-select', 'fixture.table-select'],
  ].map(([formlyType, id]) => ({
    formlyType: formlyType!,
    defaultProfile: { id: id!, version: 1 },
    variants: [],
  })),
  wrappers: [
    {
      identity: { id: 'fixture.section-card-wrapper', version: 1 },
      wrapperName: 'section-card',
      evidence: 'declared',
      parts: [declaredPart('heading', 'heading')],
      preconditions: [],
      unknowns: [],
    },
  ],
};
